@startuml
title:授权结果查询
autonumber
mq->server:消费队列内容
server->chan:查询授权智能合约结果
chan-->server:返回查询结果
server->server:判断查询结果
alt 执行成功
server->server:更新t_file_info的表状态
server->server:记录操作流水信息
server-->web:推送一个消息到mqtt中
else 执行失败
server->server:更新t_file_info的表状态为失败
server->server:记录操作日志
server-->web:推送一个消息到mqtt中
else 执行中
server->mq:返回到rabbitMq中
else 超时
server->server:判断当前超时次数 是否大于指定次数
alt 重试次数小于指定次数
server->mq:将此消息重新放入rabbitMq中
else 重试次数大于指定次数
server->server: 将此消息记录到数据库中
end
end

@enduml