@startuml
title: 文件上传
autonumber
web->web:用户选择文件
web->server:请求文件上传接口
server->server:产生文件摘要
server->server:对文件进行ccks加密,pack是服务器预先配置
server->chan:调用上链合约
note left:nonce 怎么处理？
chan->server:返回结果
server->server:保存文件到本地
server->chan:调用查询智能合约处理结果
chan-->server:返回处理结果
server->server:判断处理结果
alt 处理未完成
server->mq:将当前hash 放到mq队列中
server->web:返回当前hash处理中
web->web:通过mq消息订阅当前hash主题进行监听
else 处理成功
server->server:保存t_file_info,t_file_enc,t_user_file
server->server:保存当前文件操作流水表，fileId,cUserId,时间，操作结果
server-->web:返回处理成功
else 处理失败
server->server:删除本地文件
server->server:保存当前文件操作流水表，fileId,cUserId,时间，操作结果
server-->web:返回处理失败的原因
end
@enduml