@startuml
title:用户登录
autonumber
pro->pro:用户扫一扫二维码/手动启动小程序
pro->pro:判断用户是否需要重新登录
alt 需要重新登录
pro->com:用户登录
note left: code
com->wx: 通过code到和appSecret请求微信服务端
wx-->com:返回授权信息
alt code 已过时 | 请求超时
com-->pro:返回code已过期的错误提示信息
else 正常返回
com->com:取出返回的openId ,通过openId 找到用户的cUserId
alt 用户不存在
com-->pro:返回用户不存在错误码
else  用户已存在
com->com:通过cUserid找到用户实名信息
alt 实名信息不存在
com->pro:返回用户未实名
else 实名信息已存在
com->com:判断用户的卡号是否已开通
alt 卡号未开通
com->com:查询t_brand_info表查询品牌号和机构号开卡
com->com:删除用户老的缓存信息
com->com:开卡成功缓存卡密钥信息
com-->pro:返回userid,登录token,实名状态，小区信息
else 卡号已开通
com->com:删除用户老的缓存信息
com->com:缓存卡密钥信息
com-->pro:返回userid,登录token,实名状态，小区信息
end
end
end
end
else 不需要重新登录
pro->pro:判断当前启动小程序的方式
alt 手动启动小程序
pro->pro:跳转到首页
else 扫一扫启动小程序
pro->pro:跳转到中间页面
pro->com:请求服务端获取二维码的类型
com-->pro:返回二维码的类型
pro->pro:根据二维码的类型不同跳转不同的页面
end
end
@enduml