@startuml
title:使用场景
autonumber
APP->SDK:加载SDK 传入APPId,APP包名
SDK->TSM:校验APPID和APP包名的关系
TSM->TSM:根据APPID 查询配置
TSM->TSM:校验包名是否一致
TSM-->SDK:返回校验结果
SDK->SDK:校验失败 提示无权限
SDK->SDK:加载设备SE
SDK->TSM:加载用户SE APPID
TSM->TSM:申请用户se，根据APPID开通默认虚拟卡
TSM-->SDK:返回申请用户se的结果
SDK->SDK:加载用户SE
SDK->SDK:设置支付密码
SDK->SDK:找回虚拟卡
...
APP->APP:购物车内进行支付
APP->业务服务端:将订单号信息进行签名
业务服务端-->APP:返回订单信息和签名信息
APP->SDK:加载SDK,将订单信息和订单签名，商户号传入
SDK->SDK:展示支付信息
SDK->支付服务端:根据商户号，金额，订单信息，订单签名获取支付活动信息
支付服务端->支付服务端:根据订单信息里面的渠道号获取渠道配置，验证签名
支付服务端-->SDK:返回支付活动信息
SDK->支付服务端:调用消费接口
支付服务端->支付服务端:验证订单号是否重复，调用SDZW消费
支付服务端-->SDK:返回支付结果
支付服务端-->业务服务端:异步通过订单信息里面的回调地址通知订单支付结果
SDK-->APP:支付结果
APP->业务服务端:查询支付结果
业务服务端->支付服务端:查询支付结果
支付服务端-->业务服务端:返回支付结果
业务服务端-->APP:返回支付结果
@enduml